# Loosely based upon:
#   https://github.com/actions/starter-workflows/blob/main/ci/php.yml

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        php-version: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4]
        protocol: [ 'json', 'msgpack' ]
        ignorePlatformReq: [ '' ]

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          submodules: 'recursive'
          persist-credentials: false

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: error_reporting=E_ALL

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        env:
          IGNORE_PLATFORM_REQ: ${{ matrix.ignorePlatformReq }}
        run: composer install --prefer-dist --no-progress --no-suggest $IGNORE_PLATFORM_REQ

      # the test script is configured in composer.json.
      # see: https://getcomposer.org/doc/articles/scripts.md
      - name: Run test
        env:
          PROTOCOL: ${{ matrix.protocol }}
        run: composer run-script test
