# Loosely based upon:
#   https://github.com/actions/starter-workflows/blob/main/ci/php.yml

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4]
        protocol: [ 'json', 'msgpack' ]
        ignorePlatformReq: [ '' ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: error_reporting=E_ALL

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest ${{ matrix.ignorePlatformReq }}

      # the test script is configured in composer.json.
      # see: https://getcomposer.org/doc/articles/scripts.md
      - name: Run test
        env:
          PROTOCOL: ${{ matrix.protocol }}
        run: composer run-script test
