name: Features

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    uses: ably/features/.github/workflows/sdk-features.yml@main
    permissions:
      contents: read
      deployments: write
      id-token: write
    with:
      repository-name: ably-php
    secrets: inherit
